aaproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('products/', include('products.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('join/', views.join, name='join'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('mypage/', views.mypage, name='mypage'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
import os

# Create your models here.
class User(AbstractUser):
    birthday = models.DateField(null=True)

    def profile_image_path(instance, filename):
        return f'profiles/{instance.username}/{filename}'
    
    profile_image = models.ImageField(upload_to=profile_image_path, blank=True)

    def delete(self, *args, **kargs):
        if self.profile_image:
            os.remove(os.path.join(settings.MEDIA_ROOT, self.profile_image.path))
        super(User, self).delete(*args, **kargs)

    def save(self, *args, **kwargs):
        if self.id:
            old_user = User.objects.get(id=self.id)
            if self.profile_image != old_user.profile_image:
                if old_user.profile_image:
                    os.remove(os.path.join(settings.MEDIA_ROOT, old_user.profile_image.path))
        super(User, self).save(*args, **kwargs)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm,PasswordChangeForm
from django.contrib.auth import get_user_model
from imagekit.forms import ProcessedImageField
from imagekit.processors import ResizeToFill

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = get_user_model()
        fields = ('username', 'password1', 'password2', 'last_name')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['class'] = 'form-control my-3'
        self.fields['username'].widget.attrs['placeholder'] = '아이디'

        self.fields['password1'].widget.attrs['class'] = 'form-control my-3'
        self.fields['password1'].widget.attrs['placeholder'] = '비밀번호'
        
        self.fields['password2'].widget.attrs['class'] = 'form-control my-3'
        self.fields['password2'].widget.attrs['placeholder'] = '비밀번호 확인'
        
        self.fields['last_name'].widget.attrs['class'] = 'form-control my-3'
        self.fields['last_name'].widget.attrs['placeholder'] = '이름'

class CustomUserAuthenticationForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['class'] = 'form-control my-3'
        self.fields['username'].widget.attrs['placeholder'] = '아이디'

        self.fields['password'].widget.attrs['class'] = 'form-control my-3'
        self.fields['password'].widget.attrs['placeholder'] = '비밀번호'

class CustomUserChangeForm(UserChangeForm):
    image = ProcessedImageField(
        spec_id='profiles:image',
        processors=[ResizeToFill(100,150)],
        format='JPEG',
        options={'quality' : 90},
        required=False,
    )

    class Meta(UserChangeForm):
        model = get_user_model()
        fields = ('email','last_name','profile_image',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['email'].widget.attrs['class'] = 'form-control my-3'

        self.fields['last_name'].widget.attrs['class'] = 'form-control my-3'

        self.fields['profile_image'].widget.attrs['class'] = 'form-control my-3'

class CustomUserPasswordChangeForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['new_password1'].widget.attrs['class'] = 'form-control my-3'
        
        self.fields['new_password2'].widget.attrs['class'] = 'form-control my-3'

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login as auth_login, logout as auth_logout
from django.contrib.auth.decorators import login_required
from .forms import CustomUserCreationForm, CustomUserChangeForm, CustomUserAuthenticationForm, CustomUserPasswordChangeForm
from .models import User
from django.contrib.auth import update_session_auth_hash

# Create your views here.

def login(request):
    if request.user.is_authenticated:
        return redirect('products:index')
    
    if request.method == 'POST':
        form = CustomUserAuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('products:index')
    else:
        form = CustomUserAuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)

@login_required
def logout(request):
    auth_logout(request)
    return redirect('products:index')

def join(request):
    if request.user.is_authenticated:
        return redirect('products:index')
    
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            return redirect('accounts:login')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/join.html', context)

@login_required
def delete(request):
    request.user.delete()
    auth_logout(request)
    return redirect('products:index')

@login_required
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, request.FILES, instance=request.user)
        password_form = CustomUserPasswordChangeForm(request.user, request.POST)

        if form.is_valid():
            form.save()
        if password_form.is_valid():
            password_form.save()

        return redirect('accounts:mypage')

    else:
        form = CustomUserChangeForm(instance=request.user)
        password_form = CustomUserPasswordChangeForm(request.user, request.POST)
    context = {
        'form': form,
        'password_form' : password_form,
    }
    return render(request, 'accounts/update.html', context)

# @login_required
# def change_password(request):
#     if request.method == 'POST':
#         form = CustomUserPasswordChangeForm(request.user, request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect('accounts:login')
#     else:
#         form = CustomUserPasswordChangeForm(request.user)
#     context = {
#         'form': form,
#     }
#     return render(request, 'change_password.html', context)

@login_required
def mypage(request):
    return render(request, 'accounts/mypage.html')

accounts/templates/accounts/join.html
{% extends 'base.html' %}

{% block title %}
  회원가입
{% endblock title %}

{% block content %}

  <form class="accounts-sign" action="{% url 'accounts:join' %}" method="POST">
    {% csrf_token %}

    {{ form.username }}

    {{ form.password1 }}
    <div id="password1help" class="form-text">X 영문/숫자/특수문자 2가지 이상 조합 (8~20자)<br>X 3개 이상 연속되거나 동일한 문자/숫자 제외<br>X 아이디(이메일) 제외</div>

    {{ form.password2 }}
    <div id="password2help" class="form-text">확인을 위해 이전과 동일한 비밀번호를 입력하세요.</div>

    {{ form.last_name }}

    <input class='btn btn-primary' type="submit" value="회원가입">
    <button class="btn" onclick=back()>뒤로가기</button>
  </form>
{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}
  로그인
{% endblock title %}

{% block content %}
  <form class="accounts-sign" action="{% url 'accounts:login' %}" method="POST">
    {% csrf_token %}

    {{ form.username }}

    {{ form.password }}

    <input class='btn btn-primary' type="submit" value="로그인">
    <a class='btn btn-primary' href="{% url 'accounts:join' %}">회원가입</a>
    <button class="btn" onclick=back()>뒤로가기</button>
  </form>
{% endblock content %}

accounts/templates/accounts/mypage.html
{% extends 'base.html' %}

{% block title %}
  MY쿠팡
{% endblock title %}

{% block content %}
  <h1>마이 페이지!!</h1>
  <a href="{% url 'accounts:update' %}">회원정보수정</a>
{% endblock content %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}

{% block title %}
  회원정보수정
{% endblock title %}


{% block content %}
  <form class="accounts-sign" action="{% url 'accounts:update' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    {% if request.user.image %}
      <img src="{{ request.user.image.url }}" alt="{{ request.user }}">
    {% else %}
      <img src="{% static 'img/no_image.png' %}" alt="no image">
    {% endif %}

    <label class="form-label">아이디</label>
    {{ request.user }}

    <label class="form-label">이메일</label>
    {{ form.email }}
    
    <label class="form-label">이름</label>
    {{ form.last_name }}

    <label class="form-label">비밀번호변경</label>
    {{ password_form.old_password }}
    {{ password_form.new_password1 }}
    {{ password_form.new_password2 }}

    <label for="profile_image" class="form-label">프로필 이미지</label>
    {{ form.profile_image }}

    <input class='btn btn-primary' type="submit" value="회원가입">
  </form>
{% endblock content %}