aaproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('products/', include('products.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('join/', views.join, name='join'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('mypage/', views.mypage, name='mypage'),
]

products/urls.py
from django.urls import path
from . import views

app_name = 'products'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:product_pk>/', views.detail, name='detail'),
    path('<int:product_pk>/delete/', views.delete, name='delete'),
    path('<int:product_pk>/update/', views.update, name='update'),
    path('<int:product_pk>/comments/', views.comment_create, name='comment_create'),
    path('<int:product_pk>/comments/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    path('likes/<int:product_pk>/', views.likes, name='likes'),
    path('filtering/<str:category>/<str:sort>/<str:star>/<str:price>', views.filtering, name="filtering"),
    path('search/', views.search, name='search'),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet"> 
  <title>{% block title %}{% endblock title %}</title>
  <link rel="icon" href="{% static 'img/coupang_favicon.ico' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

  <style>
    {% block style %}
    {% endblock style %}
  </style>
</head>
<body>
  {% comment %} nav bar {% endcomment %}
  
  <nav class='sticky-top bg-white' style="height:147px; box-shadow: 1px 1px 1px rgba(0,0,0,0.1);">
    <div class="nav-header">
      <div class="container d-flex justify-content-between">
        <div class="d-flex">
          <a href="">즐겨찾기</a>
          <a href="" class="dropdown-toggle">입점신청</a>
        </div>
        <div class="d-flex align-items-center">
          {% if request.user.is_authenticated %}
            <a href="{% url 'accounts:mypage' %}" class="fw-bold">{{ request.user.last_name }}</a>
            <span style='font-size:11px;'>님</span>
            <form action="{% url 'accounts:logout' %}" method='POST'>
              {% csrf_token %}
              <button type="submit" class="logout-btn">로그아웃</button>
            </form>
          {% else %}
            <a href="{% url 'accounts:login' %}">로그인</a>
            <a href="{% url 'accounts:join' %}">회원가입</a>
          {% endif %}
          <a href="">고객센터</a>
        </div>
      </div>
    </div>
    
    {% comment %} 카테고리 {% endcomment %}
    
    <div class='container d-flex align-items-center'>

      <div class="nav-parent">
        <a data-bs-toggle="collapse" href="#multiCollapseExample1" role="button" aria-expanded="false" aria-controls="multiCollapseExample1">
          <div class="nav-collapse-btn">
            <img src="https://static.coupangcdn.com/image/coupang/common/pc_header_img_sprite_180104.png" alt="#">
            <p class='collapse-text'>카테고리</p>
          </div>
        </a>

        <div class="nav-collapse collapse multi-collapse" id="multiCollapseExample1">
          <form action="">
            <div>
              <button class='cate cate-1' type="submit">패션의류/잡화</button>
            </div>
            <div>
              <button class="cate cate-2" type="submit">뷰티</button>
            </div>
            <div>
              <button class="cate cate-3" type="submit">식품</button>
            </div>
            <div>
              <button class="cate cate-4" type="submit">주방용품</button>
            </div>
            <div>
              <button class="cate cate-5" type="submit">생활용품</button>
            </div>
            
          </form>
        </div>
      </div>

      {% comment %} 검색창 {% endcomment %}
      <div class='d-flex flex-column'>
        <div class='d-flex align-items-center ms-2' style='height: 83px;'>
          <div class="ms-3">
            <a href="{% url 'products:index' %}">
              <img src="{% static 'img/coupang_logo.png' %}" alt="logo" class="logo">
            </a>
          </div>
          <div class="search-box">
            <form action="{% url 'products:search' %}" class="searchform">
              {% csrf_token %}
              <div class="category-box">
                <a class="btn btn-primary category-box" style='opacity: 0;' data-bs-toggle="collapse" href="#collapseExample5" role="button" aria-expanded="false" aria-controls="collapseExample">
                  <a href="" class="sellect-button"></a>
                  <select class="sellect-category">
                    <option id="search-option">전체</option>
                  </select>
                </a>

                <div class="search-collapse collapse multi-collapse" id="collapseExample5">
                  <div id='searchcard' class="card card-body border-0 m-0 ps-2">
                    <div>
                      <button class="search-button" type="button">전체</button>
                    </div>
                    <div>
                      <button class="search-button" type="button">패션의류_잡화</button>
                    </div>
                    <div>
                      <button class="search-button" type="button">뷰티</button>
                    </div>
                    <div>
                      <button class="search-button" type="button">식품</button>
                    </div>
                    <div>
                      <button class="search-button" type="button">주방용품</button>
                    </div>
                    <div>
                      <button class="search-button" type="button">생활용품</button>
                    </div>
                  </div>
                </div>
              </div>

              <input name="base-query" class="search-txt" type="search" placeholder="찾고 싶은 상품을 검색해보세요!" value="{{ searchdata }}">
              <a href="#" class="microphone"></a>
              <button id="search-submit" name="base-category" value="전체" class="search-btn" type="submit"></button>
            </form>
          </div>
          
          <div class="d-flex flex-column align-items-center ms-3">
            <a href="{% url 'products:create' %}"><svg width="31px" height="33px" viewBox="0 0 64.00 64.00" xmlns="http://www.w3.org/2000/svg" stroke-width="3" stroke="#646464" fill="none" transform="matrix(1, 0, 0, 1, 0, 0)"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"><circle cx="32" cy="20.14" r="11.14"></circle><path d="M54.55,56.85A22.55,22.55,0,0,0,32,34.3h0A22.55,22.55,0,0,0,9.45,56.85Z"></path></g></svg></a>
            <span class="mycoupang">마이쿠팡</span>
          </div>

          <div class="d-flex flex-column align-items-center ms-3" >
            <svg fill="#646464" width="31px" height="33px" viewBox="0 0 56 56" xmlns="http://www.w3.org/2000/svg"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"><path d="M 20.0079 39.6485 L 47.3596 39.6485 C 48.2735 39.6485 49.0703 38.8985 49.0703 37.8907 C 49.0703 36.8829 48.2735 36.1328 47.3596 36.1328 L 20.4063 36.1328 C 19.0704 36.1328 18.2501 35.1953 18.0391 33.7656 L 17.6641 31.3047 L 47.4062 31.3047 C 50.8281 31.3047 52.5859 29.1953 53.0783 25.8438 L 54.9532 13.4453 C 55.0003 13.1407 55.0468 12.7656 55.0468 12.5547 C 55.0468 11.4297 54.2030 10.6563 52.9142 10.6563 L 14.6407 10.6563 L 14.1954 7.6797 C 13.9610 5.8750 13.3048 4.9609 10.9141 4.9609 L 2.6876 4.9609 C 1.7501 4.9609 .9532 5.7813 .9532 6.7188 C .9532 7.6797 1.7501 8.5000 2.6876 8.5000 L 10.6094 8.5000 L 14.3594 34.2344 C 14.8516 37.5625 16.6094 39.6485 20.0079 39.6485 Z M 51.0623 14.1953 L 49.3987 25.4219 C 49.2110 26.8750 48.4377 27.7656 47.0548 27.7656 L 17.1485 27.7891 L 15.1563 14.1953 Z M 21.8594 51.0391 C 23.9688 51.0391 25.6563 49.375 25.6563 47.2422 C 25.6563 45.1328 23.9688 43.4453 21.8594 43.4453 C 19.7266 43.4453 18.0391 45.1328 18.0391 47.2422 C 18.0391 49.375 19.7266 51.0391 21.8594 51.0391 Z M 43.7735 51.0391 C 45.9062 51.0391 47.5939 49.375 47.5939 47.2422 C 47.5939 45.1328 45.9062 43.4453 43.7735 43.4453 C 41.6641 43.4453 39.9532 45.1328 39.9532 47.2422 C 39.9532 49.375 41.6641 51.0391 43.7735 51.0391 Z"></path></g></svg>
            <span class="mycoupang">장바구니</span>
          </div>

        </div>
        <div class="nav-rocket d-flex">
          <div class="rocket-item d-flex">
            <div>
              <img class="h-75" src="{% static 'img/rocket1.png' %}" alt="#">
            </div>
            <a href="">로켓배송</a>
          </div>
          <div class="rocket-item">
            <div>
              <img class="h-75" src="{% static 'img/rocket2.png' %}" alt="#">
            </div>
            <a href="">로켓프레시</a>
            <div>
              <img src="{% static 'img/rocket4.png' %}" alt="#">
            </div>
          </div>
          <div class="rocket-item">
            <div>
              <img src="{% static 'img/rocket3.png' %}" alt="#">
            </div>
            <a href="">쿠팡비즈</a>
            <div>
              <img src="{% static 'img/rocket4.png' %}" alt="#">
            </div>
          </div>
          <div class="rocket-item">
            <div>
              <img class="h-75" src="{% static 'img/rocket5.png' %}" alt="#">
            </div>
            <a href="">로켓직구</a>
          </div>
          <div class="rocket-item">
            <a href="">골드박스</a>
          </div>
          <div class="rocket-item">
            <a href="">와우회원할인</a>
          </div>
          <div class="rocket-item">
            <a href="">이벤트/쿠폰</a>
          </div>
          <div class="rocket-item">
            <div>
              <img src="{% static 'img/rocket6.png' %}" alt="#">
            </div>
            <a href="">착한상점</a>
            <div>
              <img src="{% static 'img/rocket4.png' %}" alt="#">
            </div>
          </div>
          <div class="rocket-item">
            <a href="">기획전</a>
          </div>
          <div class="rocket-item">
            <div>
              <img class="h-75" src="{% static 'img/rocket7.png' %}" alt="#">
            </div>
            <a href="">여행/티켓</a>
            <div>
              <img src="{% static 'img/rocket4.png' %}" alt="#">
            </div>
          </div>
        </div>
      </div>
    </div>
    {% comment %} <div class='nav-header nav-footer'></div> {% endcomment %}
  </nav>


  <section class='container'>
    {% block content %}
    {% endblock content %}
  </section>
  <footer>

  </footer>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  <script src="{% static 'js/base.js' %}"></script>
</body>
</html>