aaproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('products/', include('products.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('join/', views.join, name='join'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('mypage/', views.mypage, name='mypage'),
]

products/urls.py
from django.urls import path
from . import views

app_name = 'products'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:product_pk>/', views.detail, name='detail'),
    path('<int:product_pk>/delete/', views.delete, name='delete'),
    path('<int:product_pk>/update/', views.update, name='update'),
    path('<int:product_pk>/comments/', views.comment_create, name='comment_create'),
    path('<int:product_pk>/comments/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    path('likes/<int:product_pk>/', views.likes, name='likes'),
    path('filtering/<str:category>/<str:sort>/<str:star>/<str:price>', views.filtering, name="filtering"),
    path('search/', views.search, name='search'),
]

products/models.py
from django.db import models
from django.conf import settings
import os
from django.core.validators import MinValueValidator, MaxValueValidator
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.utils import timezone
from datetime import timedelta,datetime
from ckeditor_uploader.fields import RichTextUploadingField
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.

class Product(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_products')
    title = models.CharField(max_length=80)
    price = models.IntegerField(default=0)
    star = models.DecimalField(default=0, max_digits=5, decimal_places=1)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    count = models.IntegerField(default=1)
    category_Choices = (('패션의류_잡화', '패션의류/잡화'), ('뷰티', '뷰티'), ('식품', '식품'), ('주방용품', '주방용품'), ('생활용품', '생활용품'))
    category = models.CharField(max_length=20, choices=category_Choices)

    content = RichTextUploadingField(blank=True,null=True)
    delivery_date = models.IntegerField(default=7)

    delivery_Choices = (('로켓배송','로켓배송'), ('제트배송','제트배송'), ('로켓직구','로켓직구'), ('로켓프레시','로켓프레시'))
    delivery = models.CharField(max_length=20, choices=delivery_Choices, null=True, blank=True)
    free_shipping = models.BooleanField(default=False)
    c_avenue = models.BooleanField(default=False)
    discount_rate = models.IntegerField(default=0)
    discounted_price = models.IntegerField(default=0)

    def count_likes_user(self):
        return self.like_users.count()
    
    def __str__(self):
        return self.title

    def calculate_discount_price(self):
        return round((self.price * (1 -self.discount_rate / 100)) / 10) * 10

    def save(self,*args, **kargs):
        self.discounted_price = self.calculate_discount_price()
        super().save(*args, **kargs)


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def product_image_path(instance, filename):
        return f'products/{instance.product.pk}/{filename}'

    image = ProcessedImageField(
        upload_to=product_image_path,
        spec_id='albums:image',
        processors=[ResizeToFill(230,230)],
        format='JPEG',
        options={'quality' : 100},
        blank=True,
        null=True,
    )

    def delete(self, *args, **kargs):
        if self.image:
            os.remove(os.path.join(settings.MEDIA_ROOT, self.image.name))
        super(ProductImage, self).delete(*args, **kargs)

    def save(self, *args, **kwargs):
        if self.id:
            old_post = ProductImage.objects.get(id=self.id)
            if self.image != old_post.image:
                if old_post.image:
                    os.remove(os.path.join(settings.MEDIA_ROOT, old_post.image.name))
        super(ProductImage, self).save(*args, **kwargs)

class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    content = models.TextField(null=False)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    star = models.IntegerField(default=5, validators=[MinValueValidator(1), MaxValueValidator(5)])
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    @property
    def created_string(self):
        time = datetime.now(tz=timezone.utc) - self.created_at

        if time < timedelta(minutes=1):
            return '방금 전'
        elif time < timedelta(hours=1):
            return str(int(time.seconds / 60)) + '분 전'
        elif time < timedelta(days=1):
            return str(int(time.seconds / 3600)) + '시간 전'
        elif time < timedelta(days=7):
            time = datetime.now(tz=timezone.utc).date() - self.created_at.date()
            return str(time.days) + '일 전'
        else:
            return self.strftime('%Y-%m-%d')


class CommentImage(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name='comment_img')

    def comment_image_path(instance, filename):
        return f'comments/{instance.comment.pk}/{filename}'
    
    comment_image = ProcessedImageField(
        upload_to=comment_image_path,
        spec_id='albums:image',
        processors=[ResizeToFill(230,230)],
        format='JPEG',
        options={'quality' : 100},
        blank=True,
        null=True,
    )

    def delete(self, *args, **kargs):
        if self.comment_image:
            os.remove(os.path.join(settings.MEDIA_ROOT, self.comment_image.name))
        super(CommentImage, self).delete(*args, **kargs)

    def save(self, *args, **kwargs):
        if self.id:
            old_post = CommentImage.objects.get(id=self.id)
            if self.comment_image != old_post.comment_image:
                if old_post.comment_image:
                    os.remove(os.path.join(settings.MEDIA_ROOT, old_post.comment_image.name))
        super(CommentImage, self).save(*args, **kwargs)

products/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from .models import Product, Comment, ProductImage, CommentImage
from .forms import ProductForm, CommentForm, ProductImageForm, CommentImageForm
from django.db.models import Q
from django.conf import settings
import os

# import ModelViewSet
# from .serializers import ProductSerializer

# Create your views here.

def index(request):
    products = Product.objects.all()
    product_images = []
    for product in products:
        images = ProductImage.objects.filter(product=product)
        if images:
            product_images.append((product, images[0]))
        else:
            product_images.append((product, ''))
    
    context = {
        'product_images': product_images,
        'sor': None,
        'cate': None,
        'sta': None,
        'pri': None,
        'query1': '',
        'query2': '',
        'searchdata': '',
    }
    return render(request, 'products/index.html',context)

def search(request):
    query = request.GET.get('base-query','')
    category = request.GET.get('base-category')

    if category != '전체':
        products = Product.objects.filter(category=category)
    else:
        products = Product.objects.all()

    if query:
        products = products.filter(
            Q(title__icontains=query)|
            Q(content__icontains=query)|
            Q(category__icontains=query)|
            Q(delivery__icontains=query)
        )

    product_images = []
    for product in products:
        images = ProductImage.objects.filter(product=product)
        if images:
            product_images.append((product, images[0]))
        else:
            product_images.append((product, ''))
    
    context = {
        'product_images': product_images,
        'cate': category,
        'sor' : None,
        'sta' : None,
        'pri' : None,
        'query1' : '',
        'query2' : '',
        'searchdata': query,
    }
    return render(request, 'products/index.html',context)

def filtering(request, category=None, sort=None, star=None, price=None):
    products = Product.objects.all()
    q1 = request.GET.get('q1')
    q2 = request.GET.get('q2')

    if category != 'None':
        products = func_category(category)
  
    if sort != 'None':
        products = func_sort(sort, products)
    
    if star != 'None':
        products = func_star(star, products)

    if q1 and q2:
        products = func_price_search(q1, q2, products)
        price = 'None'
    else:
        q1 = ''
        q2 = ''
    
    if price != 'None':
        products = func_price(price, products)
        
    
   
    product_images = []
    for product in products:
        images = ProductImage.objects.filter(product=product)
        if images:
            product_images.append((product, images[0]))
        else:
            product_images.append((product, ''))

    context = {
        'product_images': product_images,
        'cate': category,
        'sor' : sort,
        'sta' : star,
        'pri' : price,
        'query1' : q1,
        'query2' : q2,
        'searchdata' : '',
    }
    return render(request, 'products/index.html',context)

def func_category(c):
    if c == 'c_avenue':
        return Product.objects.filter(c_avenue = True)
    elif c == '무료배송':
        return Product.objects.filter(free_shipping = True)
    else:
        return Product.objects.filter(
            Q(category = c)|
            Q(delivery = c)
        )

def func_sort(s, queryset):
    if s == '최신순':
        return queryset.order_by('-pk')
    elif s == '별점순':
        return queryset.order_by('-star')
    elif s == '할인순':
        return queryset.order_by('-discount_rate')
    elif s == '낮은가격순':
        return queryset.order_by('discounted_price')
    elif s == '높은가격순':
        return queryset.order_by('-discounted_price')

def func_star(st, queryset):
    if st == '4':
        return queryset.filter(star__gte=4)
    elif st == '3':
        return queryset.filter(star__gte=3)
    elif st == '2':
        return queryset.filter(star__gte=2)
    elif st == '1':
        return queryset.filter(star__gte=1)
    else:
        return queryset
        
def func_price(p, queryset):
    if p == '1만원 미만':
        return queryset.filter(discounted_price__lt=10000)
    if p == '1만원~2만원':
        return queryset.filter(discounted_price__lt=20000, discounted_price__gte=10000)
    if p == '2만원~3만원':
        return queryset.filter(discounted_price__lt=30000, discounted_price__gte=20000)
    if p == '3만원~4만원':
        return queryset.filter(discounted_price__lt=40000, discounted_price__gte=30000)
    if p == '4만원 이상':
        return queryset.filter(discounted_price__gte=40000)
    else:
        return queryset
    
def func_price_search(q1, q2, queryset):
    return queryset.filter(discounted_price__lte=q2, discounted_price__gte=q1)

@login_required
def create(request):
    if request.method == 'POST':
        form = ProductForm(request.POST)
        files = request.FILES.getlist("image")
        if form.is_valid():
            f = form.save(commit=False)
            f.user = request.user
            f.save()
            for i in files:
                ProductImage.objects.create(image=i, product=f)
            return redirect('products:detail', f.pk)
        else:
            print(form.errors)
    else:
        product_form = ProductForm()
        image_form = ProductImageForm()
    context = {'product_form': product_form, 'image_form':image_form,}
    return render(request, 'products/create.html', context)

def update_product_star(sender, instance, **kwargs):
    product = instance.product
    comments = Comment.objects.filter(product=product)
    star_sum = sum([comment.star for comment in comments])
    star_avg = star_sum / comments.count()
    product.star = star_avg
    product.save()

def detail(request, product_pk):
    product = Product.objects.get(pk=product_pk)
    comments = product.comment_set.all()

    if comments:
        star_sum = sum([comment.star for comment in comments])
        star_avg = star_sum / comments.count()
        product.star = round(star_avg,1)
        product.save()

    product_images = []
    images = ProductImage.objects.filter(product=product)
    if images:
        product_images.append((product, images))
    else:
        product_images.append((product, ''))

    context = {
        'product':product,
        'product_images':product_images,
        'comments':comments,
        'like_count':product.count_likes_user(),
    }
    return render(request, 'products/detail.html',context)

@login_required
def delete(request, product_pk):
    product = Product.objects.get(pk=product_pk)
    if request.user == product.user:
        product.delete()
    return redirect('products:index')

@login_required
def update(request, product_pk):
    product = Product.objects.get(pk=product_pk)
    delete_images = product.image_set.all()
    images = ProductImage.objects.filter(product=product)

    if request.method == 'POST':
        form = ProductForm(request.POST, instance=product)
        files = request.FILES.getlist("image")
        if form.is_valid():
            f = form.save(commit=False)
            f.user = request.user
            f.save()
            if request.FILES.get('image'):
                if request.POST.get('sub') == '수정':
                    for i in delete_images:
                        i.delete()

            for i in files:
                ProductImage.objects.create(image=i, product=f)
            return redirect('products:index')
        else:
            print(form.errors)
    else:
        productform = ProductForm(instance=product)
        imageform = ProductImageForm()
    context = {
        'productform': productform,
        'imageform': imageform,
        'images': images
        }
    return render(request, 'products/update.html', context)

# if request.method == 'POST':
#         form = ProductForm(request.POST)
#         files = request.FILES.getlist("image")
#         if form.is_valid():
#             f = form.save(commit=False)
#             f.user = request.user
#             f.save()
#             for i in files:
#                 ProductImage.objects.create(image=i, product=f)
#             return redirect('products:index')

@login_required
def comment_create(request, product_pk):
    product = Product.objects.get(pk=product_pk)
    
    if request.method == "POST":
        comment_form = CommentForm(request.POST)
        files = request.FILES.getlist('comment_image')
        
        if comment_form.is_valid():
            c = comment_form.save(commit=False)
            c.product = product
            c.user = request.user
            c.star = request.POST.get('star_rating')
            c.save()

            for i in files:
                CommentImage.objects.create(comment_image=i, comment=c)

            return redirect('products:detail', product_pk)

    else:
        comment_form = CommentForm()
        commentimage_form = CommentImageForm()
    context = {
        'comment_form':comment_form,
        'commentimage_form':commentimage_form,
        'product':product,
    }
    return render(request,'products/comment_create.html', context)

@login_required
def comment_delete(request, product_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    if request.user == comment.user:
        comment.delete()
    return redirect('products:detail', product_pk)

@login_required
def likes(request, product_pk):
    product = Product.objects.get(pk=product_pk)
    if product.like_users.filter(pk=request.user.pk).exists():
        product.like_users.remove(request.user)
    else:
        product.like_users.add(request.user)
    return redirect('products:index', product_pk)

products/templates/products/comment_create.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
  .comment_star {
    width: 30px;
    margin-bottom: 30px;
    margin-right: 5px;
    border: none;
    background-color: white;
    padding: 0;
  }

  .comment_star img {
    width: 100%;
  }
{% endblock style %}

{% block content %}
  <h1>comment create</h1>
  <hr>
  <form action="{% url 'products:comment_create' product.pk %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class='d-flex'>
      <button type="button" class='comment_star' id="star1" data-value="1">
        <img src="{% static 'img/orange_star.png' %}" id="img1" alt="orangestar" data-value="1">
      </button>
      <button type="button" class='comment_star' id="star2" data-value="2">
        <img src="{% static 'img/orange_star.png' %}" id="img2" alt="orangestar" data-value="2">
      </button>
      <button type="button" class='comment_star' id="star3" data-value="3">
        <img src="{% static 'img/orange_star.png' %}" id="img3" alt="orangestar" data-value="3">
      </button>
      <button type="button" class='comment_star' id="star4" data-value="4">
        <img src="{% static 'img/orange_star.png' %}" id="img4" alt="orangestar" data-value="4">
      </button>
      <button type="button" class='comment_star' id="star5" data-value="5">
        <img src="{% static 'img/orange_star.png' %}" id="img5" alt="orangestar" data-value="5">
      </button>
    </div>
    {{ comment_form.as_p }}
    {{ commentimage_form.as_p }}

    <button id="star_rating" name="star_rating" value="5" type="submit">리뷰 작성</button>
  </form>

  <script>

    document.addEventListener('DOMContentLoaded', () => {
      const starBtns = document.querySelectorAll('.comment_star');
      const starRating = document.querySelector('#star_rating');
      starBtns.forEach((btn) => {
        btn.addEventListener('click', (event) => {
          const value = event.target.getAttribute('data-value');

          starRating.value = value;
          starBtns.forEach((btn) => {
            const img = btn.querySelector('img');
            const attr = btn.getAttribute('data-value')
            console.log(attr)
            if (attr <= value) {
              img.src = "/static/img/orange_star.png";
              img.alt = "orange_star"
            } else {
              img.src = "/static/img/gray_star.png";
              img.alt = "gray_star"
            }
          });
        });
      });
    });

  </script>

{% endblock content %}

products/templates/products/create.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  쿠팡
{% endblock title %}

{% block content %}
  <div class='d-flex justify-content-center'>

    <form class="create-form" action="{% url 'products:create' %}" method='POST' enctype='multipart/form-data'>
      {% csrf_token %}
      {{ product_form.media }}
  
      <label class='create-label'>제품 이름</label>
      {{ product_form.title }}
  
      <label class='create-label'>제품 설명</label>
      {{ product_form.content }}
  
      <label class='create-label'>제품 가격</label>
      {{ product_form.price }}

      <label class='create-label'>할인율</label>
      {{ product_form.discount_rate }}
  
      <label class='create-label'>배송 기한</label>
      {{ product_form.delivery_date }}
  
      <label class='create-label'>카테고리</label>
      {{ product_form.category }}
  
      <label class='create-label'>배송 방법</label>
      {{ product_form.delivery }}
  
      <div class='create-bool d-flex justify-content-between align-items-center'>
        <label class='create-label'>무료배송</label>
        {{ product_form.free_shipping }}
    
        <label class='create-label'>C.에비뉴</label>
        {{ product_form.c_avenue }}
      </div>
  
      <div>
        <label class='create-label'>제품 사진</label>
        {{ image_form.image }}
      </div>
  
      <div class='d-flex flex-column align-items-center'>

        <div>
          <button class='create-register create-hover' type="submit" class='btn'>등록하기</button>
        </div>

        <div>
          <button class="create-deregister create-hover" onclick=back()>등록취소</button>
        </div>

      </div>
    </form>

  </div>

  <link rel="stylesheet" type="text/css" href="{% static 'css/create.css' %}">
  <script src="https://cdn.ckeditor.com/ckeditor5/34.0.0/classic/ckeditor.js"></script>
  <script src="https://cdn.ckeditor.com/ckeditor5/34.0.0/classic/translations/ko.js"></script>
  <script>
    ClassicEditor.create( document.querySelector( '#editor' ), {
      language: "ko"
    } );
  </script>
{% endblock content %}

products/templates/products/detail.html
{% extends 'base.html' %}
{% load static %}
{% load customtag %}
{% block title %}
  쿠팡
{% endblock title %}

{% block content %}
  <h1>디테일</h1>

  {{ product.content|safe }}

  {% for pimage in product.productimage_set.all %}
    {% if pimage.image %}
      <div>
        <img src="{{ pimage.image.url }}" alt="#">
      </div>
    {% endif %}
  {% endfor %}

  {{product.star}}

  <span class="star-back">
    <span class="star-star" style="width:{{ product.star|total_star }}%;"></span>
  </span>
  <form action="{% url 'products:delete' product.pk %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="삭제">
  </form>
  <a class='btn btn-primary' href="{% url 'products:update' product.pk %}">수정</a>
  <a class='btn btn-primary' href="{% url 'products:index' %}">메인</a>
  <a class='btn btn-primary' href="{% url 'products:comment_create' product.pk %}">댓글 작성</a>

  {% for comment in comments %}
    <div class="comment">
      <h4>{{ comment.title }}</h4>
      <p>{{ comment.content }}</p>
      <div class='d-flex'>
        <div class='d-flex align-items-center me-1' style='width: 18px;'>
          <img class='w-100' src="{% static 'img/orange_star.png' %}" alt="">
        </div>
        <div>
          {{ comment.star }}.0 / 5.0
        </div>
      </div>
      <p>{{ comment.created_string }}</p>
      <div class="comment-images">
        {% for cimage in comment.comment_img.all %}
          {% if cimage.comment_image %}
            <img src="{{ cimage.comment_image.url }}" alt="{{ comment.title }}">
          {% endif %}
        {% endfor %}
      </div>
    </div>
  {% endfor %}


{% endblock content %}

products/templates/products/update.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  쿠팡
{% endblock title %}

{% block content %}
  <div>
    <h1>수정</h1>
  </div>
{% endblock content %}